spring.application.name=worker-service
# spring.application.name=worker-service
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/asyncevents
spring.datasource.username=a_home
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Hide Hibernate SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Worker Service Consumer
spring.kafka.consumer.group-id=worker-group
spring.kafka.consumer.auto-offset-reset=earliest

# Multiple Consumers
spring.kafka.listener.concurrency=3

# Log Cleanup
logging.level.org.hibernate=ERROR
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN

# Keep Worker logs visible
logging.level.com.example.workerservice=INFO


server.port=8081
spring.jpa.open-in-view=false