spring.application.name=AsyncEvents

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/asyncevents
spring.datasource.username=a_home
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Day 12 - Hide Hibernate SQL spam
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Docker se kafka pull
spring.kafka.bootstrap-servers=localhost:9092

# day3
spring.kafka.consumer.group-id=task-group
spring.kafka.consumer.auto-offset-reset=earliest

# Day 12 - Multiple Consumers
spring.kafka.listener.concurrency=3

# Day 12 - Log Cleanup
logging.level.org.hibernate=ERROR
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN

# Keep our application logs visible
logging.level.com.example.asyncevents=INFO