spring.application.name=AsyncEvents
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/asyncevents
spring.datasource.username=a_home
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Docker se kafka pull
spring.kafka.bootstrap-servers=localhost:9092