# spring.application.name=AsyncEvents

# # Database Connection
# spring.datasource.url=jdbc:postgresql://localhost:5432/asyncevents
# spring.datasource.username=a_home
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=update

# # Day 12 - Hide Hibernate SQL spam
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=true

# # Docker se kafka pull
# spring.kafka.bootstrap-servers=localhost:9092

# # day3
# spring.kafka.consumer.group-id=task-group
# spring.kafka.consumer.auto-offset-reset=earliest

# # Day 12 - Multiple Consumers
# spring.kafka.listener.concurrency=3

# # Day 12 - Log Cleanup
# logging.level.org.hibernate=ERROR
# logging.level.org.apache.kafka=WARN
# logging.level.org.springframework.kafka=WARN

# # Keep our application logs visible
# logging.level.com.example.asyncevents=INFO

spring.application.name=AsyncEvents

# Database Connection

# Day 18 - Docker Compose
# Use DB_URL if provided (Docker), otherwise use localhost (Local Development)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/asyncevents}

# Day 18 - Docker Compose
# Environment variable support for Docker
spring.datasource.username=${DB_USERNAME:a_home}

# Day 18 - Docker Compose
# Environment variable support for Docker
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

# Day 12 - Hide Hibernate SQL spam
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# Docker se kafka pull

# Day 18 - Docker Compose
# Uses Docker service name 'kafka' inside containers, localhost otherwise
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# day3
spring.kafka.consumer.group-id=task-group
spring.kafka.consumer.auto-offset-reset=earliest

# Day 12 - Multiple Consumers
spring.kafka.listener.concurrency=3

# Day 12 - Log Cleanup
logging.level.org.hibernate=ERROR
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN

# Keep our application logs visible
logging.level.com.example.asyncevents=INFO